### ISSUE TITLE
Vowel signs overlap on U+25CC DOTTED CIRCLE

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tagalog#5]
### Font
NotoSansTagalog-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/tagalog/releases/tag/NotoSansTagalog-v2.001
Date: 2022-09-16

### Font version
Version 2.001

### Issue
Doubled vowel signs overlap each other when applied to U+25CC DOTTED CIRCLE.

### Character data
◌ᜒᜒ◌ᜓᜓ
U+25CC DOTTED CIRCLE
U+1712 TAGALOG VOWEL SIGN I
U+1712 TAGALOG VOWEL SIGN I
U+25CC DOTTED CIRCLE
U+1713 TAGALOG VOWEL SIGN U
U+1713 TAGALOG VOWEL SIGN U

### Screenshot
![◌ᜒᜒ◌ᜓᜓ](https://user-images.githubusercontent.com/1124347/190708154-ef096bf4-26cb-40d2-a238-9405326d9ebb.png)

**Comment by simoncozens** [comment]
This is essentially a tooling problem (reported as https://github.com/googlefonts/ufo2ft/issues/754). The solution I've gone with is to pretend this is a Latin font to stop ufo2ft treating it as a USE script. Ugly, but it works, and we're not doing any kind of clever layout with this font anyway.
