### ISSUE TITLE
Combining characters alignment with base characters

### ISSUE THREAD

**Issue by ChiefMikeK** [notofonts/tagalog#7]
### Title 
  > Combining characters alignment with base characters.

### Font 
  > 'NotoSansTagalog-Regular.ttf'  
  
### Where the font came from.

  >   Site: https://notofonts.github.io/  
  >   Date: 2022-09-16  
  > just after FIRST CI run had finished but before metadata updated re-run and Deployed! 

### Font Version
  > 2.001007 

### OS name and version
  > Andriod 10 [Huawei Matepad]

### Application name and version
  > FontViewer `ru.ai.fontviewer.apk` version 1.28 (44)
  
### Issue
  > Multiple issues as per screenshot 
1. Minor VERT alignment of `U+1708, 170A, 170E, 1710` {base character is too low}.
2. Horizontal alignment of `U+1700, 1701, 1702, 1704` with combining vowels and virama (way off center).
3. Others are slightly off center both axis's.
4. ` ᜍᜒ ` `U+171D` and combining characters fail to join. 
5. fontbake reports missing NBSP `U+00A0` 
   > It could be useful in certain conext?

### Character data
 ᜃᜒ ᜃ᜕ ᜃᜓ ᜃ

 ᜀᜒᜁᜒᜂᜒᜃᜒᜄᜒᜅᜒᜆᜒᜇᜒᜈᜒᜉᜒᜊᜒᜋᜒᜌᜒᜍᜒᜎᜒᜏᜒᜐᜒᜑᜒ⏌ᜒ

 ᜀᜓᜁᜓᜂᜓᜃᜓᜄᜓᜅᜓᜆᜓᜇᜓᜈᜓᜉᜓᜊᜓᜋᜓᜌᜓᜍᜓᜎᜓᜏᜓᜐᜓᜑᜓ⏌ᜓ

 ᜀ᜔ᜁ᜔ᜂ᜔ᜃ᜔ᜄ᜔ᜅ᜔ᜆ᜔ᜇ᜔ᜈ᜔ᜉ᜔ᜊ᜔ᜋ᜔ᜌ᜔ᜍ᜔ᜎ᜔ᜏ᜔ᜐ᜔ᜑ᜔⏌᜔
   

### Screenshot
![NotoTagalogErrata](https://user-images.githubusercontent.com/20070053/190790026-9a186253-b6ae-4ef2-a95e-d1eae3a912f2.png)

### Harfbuzz hb-view and hb-shape
 > I'll submit later with a follow up, if needed :neckbeard:

### Fontview
  * n/a
### Fontdiff
  * n/a

### Ping 
 > @ctrlcctrlv are any of these `.glyph`'s this from your commit / PR? 
 I was hopping to see forks consolidated / published into ASOP Android-13🏁 but too late now🐈‍⬛
 
 [ctrlcctrlv/Noto-Sans-Tagalog V3.0](https://github.com/ctrlcctrlv/Noto-Sans-Tagalog )
 : Noto Sans Tagalog as a variable font.

**Comment by ctrlcctrlv** [comment]
This is not a real defect. The vowels cannot receive vowel marks, that makes no sense. The RA combination is a known issue, please see the documentation in my branch. Hopefully it will correct itself over time as U14.0 works its way into more libraries/OS versions, I can't do anything about it (in a sane way at least).

**Comment by ctrlcctrlv** [comment]
Regarding the non-greenboxed letters, I chose those non-aligned positions based on my own type design judgment, there is no rule of the Tagalog script that they _must_ be at 50% glyph width, native calligraphers don't do that, etc.

**Comment by simoncozens** [comment]
Looks like all of these are basically non-issues.
